name: Build and Publish storybook docs to GitHub Pages

on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        uses: deploy-docs
        with:
          path: storybook-static
          build_command: npm run build-storybook
