name: Build and Deploy storybook docs

on:
  push:
    branches:
      - 'main'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.1
      - name: Install and Build
      run: |
          npm install
          npm run deploy-storybook -- --ci